### ISSUE TITLE
[Android Auto] Functionality checklist

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android-examples#81]
There is a set of requirements from Google's quality-guidelines. This issue is to provide visibility for how to handle each issue. It also shows which issues do not yet have a public example.

https://developer.android.com/docs/quality-guidelines/car-app-quality#functionality

Code | Description
-- | --
NF-1 | The app must provide turn-by-turn navigation directions.
NF-2 | The app draws only map content on the surface of the navigation templates. Text-based turn-by-turn directions, lane guidance, and estimated arrival time must be displayed on the relevant components of the Navigation template. Additional information relevant to the drive (e.g., speed limit, road obstructions) can be drawn on the right side of the map.
NF-3 | When the app provides text-based turn-by-turn directions, then it must also trigger navigation notifications. ([Learn How](https://developer.android.com/training/cars/apps/navigation#turn-by-turn-notifications))
NF-4 | When the navigation app provides text-based turn-by-turn directions, it must send next-turn information to the vehicle’s cluster display. ([Learn How](https://developer.android.com/training/cars/apps/navigation#navigation-metadata))
NF-5 | The app must not provide turn-by-turn notifications, voice guidance, or cluster information when another navigation app is providing turn-by-turn instructions. ([Learn How](https://developer.android.com/training/cars/apps/navigation#starting-ending-stopping-navigation))
NF-6 | The app must handle navigation requests from other Android Auto apps. ([Learn How](https://developer.android.com/training/cars/apps/navigation#support-navigation-intents))
NF-7 | The app must provide a “test drive” mode that simulates driving. ([Learn How](https://developer.android.com/training/cars/apps/navigation#simulating-navigation))
NF-8 | The app must draw a light-themed or dark-themed map when instructed to do so. ([Learn How](https://developer.android.com/training/cars/apps/navigation#dark-mode))

## Status page for this examples repository

- [x] NF-1: See the [ActiveGuidanceScreen](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/android-auto/src/main/java/com/mapbox/examples/androidauto/car/navigation/ActiveGuidanceScreen.kt). See the [audioguidance](https://github.com/mapbox/mapbox-navigation-android-examples/tree/main/android-auto/src/main/java/com/mapbox/androidauto/navigation/audioguidance) module for voice guidance.
- [x] NF-2: See the [MapboxCarMap](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/android-auto/src/main/java/com/mapbox/androidauto/car/map/MapboxCarMap.kt) for map rendering. And [ActiveGuidanceScreen](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/android-auto/src/main/java/com/mapbox/examples/androidauto/car/navigation/ActiveGuidanceScreen.kt) for text based navigation info. [SpeedLimitWidget](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/android-auto/src/main/java/com/mapbox/androidauto/car/navigation/speedlimit/SpeedLimitWidget.kt) to show speed limit on map. [CarLanesImageRenderer](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/android-auto/src/main/java/com/mapbox/androidauto/car/navigation/lanes/CarLanesImageRenderer.kt) to show lange guidance images.
- [x] NF-3: See the [TripNotificationInterceptor](https://github.com/mapbox/mapbox-navigation-android/blob/c53c5b119702cd7423f3179baa04cca57d16e6c4/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L1085)
- [x] NF-4: See the [MapboxCarNavigationManager](https://github.com/mapbox/mapbox-navigation-android-examples/blob/9079fe8551ca12a56c6ba05dbc1bb3fc985f2722/android-auto/src/main/java/com/mapbox/androidauto/MapboxCarNavigationManager.kt#L40)
- [x] NF-5: See the [MapboxCarNavigationManager](https://github.com/mapbox/mapbox-navigation-android-examples/blob/9079fe8551ca12a56c6ba05dbc1bb3fc985f2722/android-auto/src/main/java/com/mapbox/androidauto/MapboxCarNavigationManager.kt#L56)
- [x] NF-6: See the [GeoDeeplinkNavigateAction](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/android-auto/src/main/java/com/mapbox/androidauto/deeplink/GeoDeeplinkNavigateAction.kt)
- [x] NF-7: See the [MapboxCarNavigationManager](https://github.com/mapbox/mapbox-navigation-android-examples/blob/9079fe8551ca12a56c6ba05dbc1bb3fc985f2722/android-auto/src/main/java/com/mapbox/androidauto/MapboxCarNavigationManager.kt#L66-L70)
- [x] NF-8: See the [MapboxCarMap](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/android-auto/src/main/java/com/mapbox/androidauto/car/map/MapboxCarMap.kt)

🔉  [extension-androidauto-v0.1.0](https://github.com/mapbox/mapbox-maps-android/releases/tag/extension-androidauto-v0.1.0): The apis related to [MapboxCarMap](https://github.com/mapbox/mapbox-maps-android/blob/85552dc97a134f1bcbf923e6307e6292922f750f/extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt#L34-L36) are have been moved to a permanent solution. 

🔉  [androidauto-v0.1.0](https://github.com/mapbox/mapbox-navigation-android/releases/tag/androidauto-v0.1.0): The apis related to Mapbox Navigation have been moved to a permanent solution.
 
cc: @mapbox/navigation-android @pengdev @yunikkk

**Comment by Guardiola31337** [comment]
This is great! Thanks for cutting this ticket @kmadsen 🙇‍♂️ 

For documentation's sake we should probably start collecting all these in a separate FAQ that we can add to the public docs at some point later.

cc @truburt

**Comment by linsd75** [comment]
This is great!

**Comment by kmadsen** [comment]
`NF-4` and `NF-5` vehicle’s cluster display can be tested with a custom configuration

```
$ cat instrumentcluster.ini
[general]
touch = true
touchpad = false
controller = false
instrumentcluster = true
resolution = 800x480
dpi = 160
framerate = 30

[sensors]
location = true
night_mode = true
driving_status = true

& ./desktop-head-unit -c instrumentcluster.ini
```

<img width="1064" alt="Screen Shot 2022-03-30 at 9 59 03 AM" src="https://user-images.githubusercontent.com/3021882/160890664-2f0e08e3-b4d8-4ff6-9a19-fb1993b17a91.png">

**Comment by kmadsen** [comment]
We're considering the functionality checklist complete. All and any issues related to Mapbox Android Auto have been moved to artifacts. Any further issues will be tracked in the maps or navigation repositories

https://github.com/mapbox/mapbox-navigation-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22Android+Auto%22
https://github.com/mapbox/mapbox-maps-android/issues?q=is%3Aopen+is%3Aissue+label%3Aandroid-auto
https://github.com/mapbox/mapbox-maps-android-internal/issues?q=is%3Aopen+is%3Aissue+label%3Aandroid-auto

**Comment by Mr-Ramzan** [comment]
Hi! I know this is closed, I have an Update rejected due to Android Auto Being used in My App. @kmadsen can you please guide me to remove Android-Auto-related code I do not want my app to support Android Auto.
Can you Guide which component to exclude or any flags to disable Android Auto Support?

**Comment by kmadsen** [comment]
> Hi! I know this is closed, I have an Update rejected due to Android Auto Being used in My App. @kmadsen can you please guide me to remove Android-Auto-related code I do not want my app to support Android Auto.
Can you Guide which component to exclude or any flags to disable Android Auto Support?

@Mr-Ramzan Are you using Mapbox for Android Auto? If you are using a solution from the guide https://docs.mapbox.com/android/navigation/guides/androidauto/, will you please create an issue https://github.com/mapbox/mapbox-navigation-android/issues/new with details about your app rejection?
